Container Cluster Reverse Proxy Support
jason0x43/hacs-hubitat pull request #284
Opened 2024-08-26 02:41 UTC by JoKneeMo

Allow override of the server listening interface and disable HE POST URL updating.
Adds 2 new optional config options
- server_interface
- update_he_url

This should allow anyone running Home Assistant in Docker Swarm or Kubernetes to use this integration.
Without the ability to set the listening interface, hosts with a dynamic container IP can not connect.

UI Example:
![image](https://github.com/user-attachments/assets/c0cbb323-0620-4325-835e-897b45d877c0)

2024-08-26 02:43 UTC, JoKneeMo commented
This PR would resolve #283

2024-08-28 00:56 UTC, jason0x43 requested changes
Thanks for the contribution! I have a few minor requests, but otherwise this looks good.

2024-08-28 00:56 UTC, jason0x43 commented on custom_components/hubitat/config_flow.py
> +    update_he_url: bool = user_input.get(H_CONF_UPDATE_HE_URL)
This should be `bool | None`

2024-08-28 00:56 UTC, jason0x43 commented on custom_components/hubitat/config_flow.py
> +                    H_CONF_UPDATE_HE_URL: user_input.get(H_CONF_UPDATE_HE_URL),
For backwards compatibility, I'd prefer this be something that could default to false (e.g., "Don't update event POST URL in Hubitat") because it's going to start out disabled for users after they update.

2024-08-28 00:56 UTC, jason0x43 commented on custom_components/hubitat/hub.py
> +    def address(self) -> str | None:
Is this property used anywhere?

2024-08-28 00:56 UTC, jason0x43 commented on custom_components/hubitat/hub.py
> +    def update_he_url(self) -> bool | None:
Is this property used anywhere?

2024-08-28 00:56 UTC, jason0x43 commented on custom_components/hubitat/hubitatmaker/hub.py
> +            self._process_event, self.address, self.port or 0, self.ssl_context
Make this `self.address or '0.0.0.0'` since `create_server` expects a string value.

2024-08-28 00:56 UTC, jason0x43 commented on custom_components/hubitat/hubitatmaker/hub.py
> +    if host is not None:
`host` should never be None since this is only called from the constructor, and the constructor must be passed a host value.

2026-06-09 04:03 UTC, closed without merging